server:
  addr: "0.0.0.0:8087"

logger:
  file_name: "./auth.log"
  max_size: 50
  level: "info"

rate_limiter:
  login:
    rpm: 1
    expire_time: 60
  password:
    rpm: 1
    expire_time: 60
  ip:
    rpm: 1
    expire_time: 60
  gc_time: 90