gRPC_server:
  addr: "localhost:8112"

http_server:
  addr: "localhost:8113"

logger:
  file_name: "./auth.log"
  max_size: 50
  level: "info"

rate_limiter:
  login:
    rate: 2
    interval: 50ms
    expire_time: 10m
  password:
    rate: 3
    interval: 50ms
    expire_time: 10m
  ip:
    rate: 4
    interval: 50ms
    expire_time: 10m
  gc_time: 20m

mongo:
  addr: "localhost:27017"
  db_name: "test"