version: '3.7'

# sudo docker-compose up -d --build

services:
  antibruteforce:
    build:
      context: ../../
      dockerfile: deployments/stage/antibruteforce/Dockerfile
    image: antibruteforce:latest
    container_name: antibruteforce
    ports:
      - "8087:8087"
      - "8088:8088"
    restart: always
    depends_on:
      - redis
    networks:
      - stagenetwork
  redis:
    image: redis
    volumes:
      - redis_storage:/var/lib/grafana
    ports:
      - 6379:6379
    restart: always
    networks:
      - stagenetwork

networks:
  stagenetwork:
    driver: bridge

volumes:
  redis_storage: