version: '3.7'

# docker-compose up -d --build && docker image prune -f

services:
  antibruteforce:
    build:
      context: ../../
      dockerfile: deployments/stage/antibruteforce/Dockerfile
    image: antibruteforce:latest
    container_name: antibruteforce
    ports:
      - "8087:8087"
      - "8088:8088"
    restart: always
    depends_on:
      - mongo
    networks:
      - stagenetwork
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_storage:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - stagenetwork

networks:
  stagenetwork:
    driver: bridge

volumes:
  mongo_storage: