{
 "title": "Anti brute-force",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Administration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "antibruteforce_admin_service_request_latency_microseconds_sum"
    }
   ]
  },
  {
   "title": "Count requests",
   "type": "graph",
   "gridPos": { "h": 14, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antibruteforce_admin_service_request_count"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"500\"}"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(antibruteforce_admin_service_request_count[5m])"
    }
   ]
  },
  { "title": "Authorization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Total time (in seconds) spent serving requests by sign_in.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "antibruteforce_auth_latency_sign_in_request_sum"
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "antibruteforce_auth_latency_sign_in_request_count"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(antibruteforce_auth_latency_sign_in_request_count[1m])"
    }
   ]
  }
 ]
}